"use client";
import { FilterTime } from "@/components/FilterTime";
import { TopNFTsTable } from "@/components/NFTTopContracts/TopNFTsTable";
import { ScanLayout } from "@/components/layouts/ScanLayout";
import { useTheme } from "@/hooks/useTheme";
import { FILTER_TIME_DATA } from "@/utils/constants";
import { useState } from "react";
import { useTranslation } from "react-i18next";

const dataFor1H = [
  {
    id: "1",
    collection: "OpenSea Shared Storefront",
    type: "ERC-1155",
    volume: `${Math.random() * 100}`,
    change: `${Math.random() * 100}`,
    sales: Math.floor(Math.random() * 100),
    minPrice: `${Math.random() * 2}`,
    maxPrice: `${Math.random() * 10}`,
    transfer: `${Math.random() * 1000}`,
    owners: Math.floor(Math.random() * 100000),
    totalAssets: Math.floor(Math.random() * 1000000),
  },
  {
    id: "2",
    collection: "Parallel Avatars",
    type: "ERC-721",
    volume: `${Math.random() * 100}`,
    change: `${Math.random() * 100}`,
    sales: Math.floor(Math.random() * 100),
    minPrice: `${Math.random() * 2}`,
    maxPrice: `${Math.random() * 10}`,
    transfer: `${Math.random() * 1000}`,
    owners: Math.floor(Math.random() * 100000),
    totalAssets: Math.floor(Math.random() * 1000000),
  },
  {
    id: "3",
    collection: "alignDRAW",
    type: "ERC-721",
    volume: `${Math.random() * 100}`,
    change: `${Math.random() * 100}`,
    sales: Math.floor(Math.random() * 100),
    minPrice: `${Math.random() * 2}`,
    maxPrice: `${Math.random() * 10}`,
    transfer: `${Math.random() * 1000}`,
    owners: Math.floor(Math.random() * 100000),
    totalAssets: Math.floor(Math.random() * 1000000),
  },
  {
    id: "4",
    collection: "VeeFriends",
    type: "ERC-721",
    volume: `${Math.random() * 100}`,
    change: `${Math.random() * 100}`,
    sales: Math.floor(Math.random() * 100),
    minPrice: `${Math.random() * 2}`,
    maxPrice: `${Math.random() * 10}`,
    transfer: `${Math.random() * 1000}`,
    owners: Math.floor(Math.random() * 100000),
    totalAssets: Math.floor(Math.random() * 1000000),
  },
  {
    id: "5",
    collection: "Elemental",
    type: "ERC-721",
    volume: `${Math.random() * 100}`,
    change: `${Math.random() * 100}`,
    sales: Math.floor(Math.random() * 100),
    minPrice: `${Math.random() * 2}`,
    maxPrice: `${Math.random() * 10}`,
    transfer: `${Math.random() * 1000}`,
    owners: Math.floor(Math.random() * 100000),
    totalAssets: Math.floor(Math.random() * 1000000),
  },
  {
    id: "6",
    collection: "My Pet Hooligan",
    type: "ERC-721",
    volume: `${Math.random() * 100}`,
    change: `${Math.random() * 100}`,
    sales: Math.floor(Math.random() * 100),
    minPrice: `${Math.random() * 2}`,
    maxPrice: `${Math.random() * 10}`,
    transfer: `${Math.random() * 1000}`,
    owners: Math.floor(Math.random() * 100000),
    totalAssets: Math.floor(Math.random() * 1000000),
  },
  {
    id: "7",
    collection: "BoredApeKennelClub",
    type: "ERC-721",
    volume: `${Math.random() * 100}`,
    change: `${Math.random() * 100}`,
    sales: Math.floor(Math.random() * 100),
    minPrice: `${Math.random() * 2}`,
    maxPrice: `${Math.random() * 10}`,
    transfer: `${Math.random() * 1000}`,
    owners: Math.floor(Math.random() * 100000),
    totalAssets: Math.floor(Math.random() * 1000000),
  },
  {
    id: "8",
    collection: "CloneX",
    type: "ERC-721",
    volume: `${Math.random() * 100}`,
    change: `${Math.random() * 100}`,
    sales: Math.floor(Math.random() * 100),
    minPrice: `${Math.random() * 2}`,
    maxPrice: `${Math.random() * 10}`,
    transfer: `${Math.random() * 1000}`,
    owners: Math.floor(Math.random() * 100000),
    totalAssets: Math.floor(Math.random() * 1000000),
  },
  {
    id: "9",
    collection: "NEOSTACKEY",
    type: "ERC-721",
    volume: `${Math.random() * 100}`,
    change: `${Math.random() * 100}`,
    sales: Math.floor(Math.random() * 100),
    minPrice: `${Math.random() * 2}`,
    maxPrice: `${Math.random() * 10}`,
    transfer: `${Math.random() * 1000}`,
    owners: Math.floor(Math.random() * 100000),
    totalAssets: Math.floor(Math.random() * 1000000),
  },
  {
    id: "10",
    collection: "Project AEON",
    type: "ERC-721",
    volume: `${Math.random() * 100}`,
    change: `${Math.random() * 100}`,
    sales: Math.floor(Math.random() * 100),
    minPrice: `${Math.random() * 2}`,
    maxPrice: `${Math.random() * 10}`,
    transfer: `${Math.random() * 1000}`,
    owners: Math.floor(Math.random() * 100000),
    totalAssets: Math.floor(Math.random() * 1000000),
  },
  {
    id: "11",
    collection: "KIP Protocol",
    type: "ERC-721",
    volume: `${Math.random() * 100}`,
    change: `${Math.random() * 100}`,
    sales: Math.floor(Math.random() * 100),
    minPrice: `${Math.random() * 2}`,
    maxPrice: `${Math.random() * 10}`,
    transfer: `${Math.random() * 1000}`,
    owners: Math.floor(Math.random() * 100000),
    totalAssets: Math.floor(Math.random() * 1000000),
  },
];
const dataFor6H = [
  {
    id: "1",
    collection: "Azuki",
    type: "ERC-721",
    volume: `${Math.random() * 100}`,
    change: `${Math.random() * 100}`,
    sales: Math.floor(Math.random() * 100),
    minPrice: `${Math.random() * 2}`,
    maxPrice: `${Math.random() * 10}`,
    transfer: `${Math.random() * 1000}`,
    owners: Math.floor(Math.random() * 100000),
    totalAssets: Math.floor(Math.random() * 1000000),
  },
  {
    id: "2",
    collection: "TAROT",
    type: "ERC-721",
    volume: `${Math.random() * 100}`,
    change: `${Math.random() * 100}`,
    sales: Math.floor(Math.random() * 100),
    minPrice: `${Math.random() * 2}`,
    maxPrice: `${Math.random() * 10}`,
    transfer: `${Math.random() * 1000}`,
    owners: Math.floor(Math.random() * 100000),
    totalAssets: Math.floor(Math.random() * 1000000),
  },
  {
    id: "3",
    collection: "MutantApeYachtClub",
    type: "ERC-721",
    volume: `${Math.random() * 100}`,
    change: `${Math.random() * 100}`,
    sales: Math.floor(Math.random() * 100),
    minPrice: `${Math.random() * 2}`,
    maxPrice: `${Math.random() * 10}`,
    transfer: `${Math.random() * 1000}`,
    owners: Math.floor(Math.random() * 100000),
    totalAssets: Math.floor(Math.random() * 1000000),
  },
  {
    id: "4",
    collection: "The Memes by 6529",
    type: "ERC-1155",
    volume: `${Math.random() * 100}`,
    change: `${Math.random() * 100}`,
    sales: Math.floor(Math.random() * 100),
    minPrice: `${Math.random() * 2}`,
    maxPrice: `${Math.random() * 10}`,
    transfer: `${Math.random() * 1000}`,
    owners: Math.floor(Math.random() * 100000),
    totalAssets: Math.floor(Math.random() * 1000000),
  },
  {
    id: "5",
    collection: "Art Blocks",
    type: "ERC-721",
    volume: `${Math.random() * 100}`,
    change: `${Math.random() * 100}`,
    sales: Math.floor(Math.random() * 100),
    minPrice: `${Math.random() * 2}`,
    maxPrice: `${Math.random() * 10}`,
    transfer: `${Math.random() * 1000}`,
    owners: Math.floor(Math.random() * 100000),
    totalAssets: Math.floor(Math.random() * 1000000),
  },
  {
    id: "6",
    collection: "OVERWORLD INCARNA",
    type: "ERC-721",
    volume: `${Math.random() * 100}`,
    change: `${Math.random() * 100}`,
    sales: Math.floor(Math.random() * 100),
    minPrice: `${Math.random() * 2}`,
    maxPrice: `${Math.random() * 10}`,
    transfer: `${Math.random() * 1000}`,
    owners: Math.floor(Math.random() * 100000),
    totalAssets: Math.floor(Math.random() * 1000000),
  },
  {
    id: "7",
    collection: "Captainz",
    type: "ERC-721",
    volume: `${Math.random() * 100}`,
    change: `${Math.random() * 100}`,
    sales: Math.floor(Math.random() * 100),
    minPrice: `${Math.random() * 2}`,
    maxPrice: `${Math.random() * 10}`,
    transfer: `${Math.random() * 1000}`,
    owners: Math.floor(Math.random() * 100000),
    totalAssets: Math.floor(Math.random() * 1000000),
  },
  {
    id: "8",
    collection: "Grails III",
    type: "ERC-721",
    volume: `${Math.random() * 100}`,
    change: `${Math.random() * 100}`,
    sales: Math.floor(Math.random() * 100),
    minPrice: `${Math.random() * 2}`,
    maxPrice: `${Math.random() * 10}`,
    transfer: `${Math.random() * 1000}`,
    owners: Math.floor(Math.random() * 100000),
    totalAssets: Math.floor(Math.random() * 1000000),
  },
  {
    id: "9",
    collection: "Otherdeed",
    type: "ERC-721",
    volume: `${Math.random() * 100}`,
    change: `${Math.random() * 100}`,
    sales: Math.floor(Math.random() * 100),
    minPrice: `${Math.random() * 2}`,
    maxPrice: `${Math.random() * 10}`,
    transfer: `${Math.random() * 1000}`,
    owners: Math.floor(Math.random() * 100000),
    totalAssets: Math.floor(Math.random() * 1000000),
  },
  {
    id: "10",
    collection: "Art Blocks",
    type: "ERC-721",
    volume: `${Math.random() * 100}`,
    change: `${Math.random() * 100}`,
    sales: Math.floor(Math.random() * 100),
    minPrice: `${Math.random() * 2}`,
    maxPrice: `${Math.random() * 10}`,
    transfer: `${Math.random() * 1000}`,
    owners: Math.floor(Math.random() * 100000),
    totalAssets: Math.floor(Math.random() * 1000000),
  },
  {
    id: "11",
    collection: "The Llamas",
    type: "ERC-721",
    volume: `${Math.random() * 100}`,
    change: `${Math.random() * 100}`,
    sales: Math.floor(Math.random() * 100),
    minPrice: `${Math.random() * 2}`,
    maxPrice: `${Math.random() * 10}`,
    transfer: `${Math.random() * 1000}`,
    owners: Math.floor(Math.random() * 100000),
    totalAssets: Math.floor(Math.random() * 1000000),
  },
];
const dataFor12H = [
  {
    id: "1",
    collection: "Azuki",
    type: "ERC-721",
    volume: `${Math.random() * 100}`,
    change: `${Math.random() * 100}`,
    sales: Math.floor(Math.random() * 100),
    minPrice: `${Math.random() * 2}`,
    maxPrice: `${Math.random() * 10}`,
    transfer: `${Math.random() * 1000}`,
    owners: Math.floor(Math.random() * 100000),
    totalAssets: Math.floor(Math.random() * 1000000),
  },
  {
    id: "2",
    collection: "BoredApeYachtClub",
    type: "ERC-721",
    volume: `${Math.random() * 100}`,
    change: `${Math.random() * 100}`,
    sales: Math.floor(Math.random() * 100),
    minPrice: `${Math.random() * 2}`,
    maxPrice: `${Math.random() * 10}`,
    transfer: `${Math.random() * 1000}`,
    owners: Math.floor(Math.random() * 100000),
    totalAssets: Math.floor(Math.random() * 1000000),
  },
  {
    id: "3",
    collection: "MutantApeYachtClub",
    type: "ERC-721",
    volume: `${Math.random() * 100}`,
    change: `${Math.random() * 100}`,
    sales: Math.floor(Math.random() * 100),
    minPrice: `${Math.random() * 2}`,
    maxPrice: `${Math.random() * 10}`,
    transfer: `${Math.random() * 1000}`,
    owners: Math.floor(Math.random() * 100000),
    totalAssets: Math.floor(Math.random() * 1000000),
  },
  {
    id: "4",
    collection: "TAROT",
    type: "ERC-1155",
    volume: `${Math.random() * 100}`,
    change: `${Math.random() * 100}`,
    sales: Math.floor(Math.random() * 100),
    minPrice: `${Math.random() * 2}`,
    maxPrice: `${Math.random() * 10}`,
    transfer: `${Math.random() * 1000}`,
    owners: Math.floor(Math.random() * 100000),
    totalAssets: Math.floor(Math.random() * 1000000),
  },
  {
    id: "5",
    collection: "The Memes by 6529",
    type: "ERC-1155",
    volume: `${Math.random() * 100}`,
    change: `${Math.random() * 100}`,
    sales: Math.floor(Math.random() * 100),
    minPrice: `${Math.random() * 2}`,
    maxPrice: `${Math.random() * 10}`,
    transfer: `${Math.random() * 1000}`,
    owners: Math.floor(Math.random() * 100000),
    totalAssets: Math.floor(Math.random() * 1000000),
  },
  {
    id: "6",
    collection: "DeGods",
    type: "ERC-721",
    volume: `${Math.random() * 100}`,
    change: `${Math.random() * 100}`,
    sales: Math.floor(Math.random() * 100),
    minPrice: `${Math.random() * 2}`,
    maxPrice: `${Math.random() * 10}`,
    transfer: `${Math.random() * 1000}`,
    owners: Math.floor(Math.random() * 100000),
    totalAssets: Math.floor(Math.random() * 1000000),
  },
  {
    id: "7",
    collection: "KIP Protocol",
    type: "ERC-721",
    volume: `${Math.random() * 100}`,
    change: `${Math.random() * 100}`,
    sales: Math.floor(Math.random() * 100),
    minPrice: `${Math.random() * 2}`,
    maxPrice: `${Math.random() * 10}`,
    transfer: `${Math.random() * 1000}`,
    owners: Math.floor(Math.random() * 100000),
    totalAssets: Math.floor(Math.random() * 1000000),
  },
  {
    id: "8",
    collection: "OVERWORLD INCARNA",
    type: "ERC-721",
    volume: `${Math.random() * 100}`,
    change: `${Math.random() * 100}`,
    sales: Math.floor(Math.random() * 100),
    minPrice: `${Math.random() * 2}`,
    maxPrice: `${Math.random() * 10}`,
    transfer: `${Math.random() * 1000}`,
    owners: Math.floor(Math.random() * 100000),
    totalAssets: Math.floor(Math.random() * 1000000),
  },
  {
    id: "9",
    collection: "My Pet Hooligan",
    type: "ERC-721",
    volume: `${Math.random() * 100}`,
    change: `${Math.random() * 100}`,
    sales: Math.floor(Math.random() * 100),
    minPrice: `${Math.random() * 2}`,
    maxPrice: `${Math.random() * 10}`,
    transfer: `${Math.random() * 1000}`,
    owners: Math.floor(Math.random() * 100000),
    totalAssets: Math.floor(Math.random() * 1000000),
  },
  {
    id: "10",
    collection: "Art Blocks",
    type: "ERC-721",
    volume: `${Math.random() * 100}`,
    change: `${Math.random() * 100}`,
    sales: Math.floor(Math.random() * 100),
    minPrice: `${Math.random() * 2}`,
    maxPrice: `${Math.random() * 10}`,
    transfer: `${Math.random() * 1000}`,
    owners: Math.floor(Math.random() * 100000),
    totalAssets: Math.floor(Math.random() * 1000000),
  },
  {
    id: "11",
    collection: "KILLABEARS",
    type: "ERC-721",
    volume: `${Math.random() * 100}`,
    change: `${Math.random() * 100}`,
    sales: Math.floor(Math.random() * 100),
    minPrice: `${Math.random() * 2}`,
    maxPrice: `${Math.random() * 10}`,
    transfer: `${Math.random() * 1000}`,
    owners: Math.floor(Math.random() * 100000),
    totalAssets: Math.floor(Math.random() * 1000000),
  },
];
const dataFor1D = [
  {
    id: "1",
    collection: "TAROT",
    type: "ERC-721",
    volume: `${Math.random() * 100}`,
    change: `${Math.random() * 100}`,
    sales: Math.floor(Math.random() * 100),
    minPrice: `${Math.random() * 2}`,
    maxPrice: `${Math.random() * 10}`,
    transfer: `${Math.random() * 1000}`,
    owners: Math.floor(Math.random() * 100000),
    totalAssets: Math.floor(Math.random() * 1000000),
  },
  {
    id: "2",
    collection: "BoredApeYachtClub",
    type: "ERC-721",
    volume: `${Math.random() * 100}`,
    change: `${Math.random() * 100}`,
    sales: Math.floor(Math.random() * 100),
    minPrice: `${Math.random() * 2}`,
    maxPrice: `${Math.random() * 10}`,
    transfer: `${Math.random() * 1000}`,
    owners: Math.floor(Math.random() * 100000),
    totalAssets: Math.floor(Math.random() * 1000000),
  },
  {
    id: "3",
    collection: "SOMO Monoliths",
    type: "ERC-721",
    volume: `${Math.random() * 100}`,
    change: `${Math.random() * 100}`,
    sales: Math.floor(Math.random() * 100),
    minPrice: `${Math.random() * 2}`,
    maxPrice: `${Math.random() * 10}`,
    transfer: `${Math.random() * 1000}`,
    owners: Math.floor(Math.random() * 100000),
    totalAssets: Math.floor(Math.random() * 1000000),
  },
  {
    id: "4",
    collection: "Azuki",
    type: "ERC-1155",
    volume: `${Math.random() * 100}`,
    change: `${Math.random() * 100}`,
    sales: Math.floor(Math.random() * 100),
    minPrice: `${Math.random() * 2}`,
    maxPrice: `${Math.random() * 10}`,
    transfer: `${Math.random() * 1000}`,
    owners: Math.floor(Math.random() * 100000),
    totalAssets: Math.floor(Math.random() * 1000000),
  },
  {
    id: "5",
    collection: "DeGods",
    type: "ERC-721",
    volume: `${Math.random() * 100}`,
    change: `${Math.random() * 100}`,
    sales: Math.floor(Math.random() * 100),
    minPrice: `${Math.random() * 2}`,
    maxPrice: `${Math.random() * 10}`,
    transfer: `${Math.random() * 1000}`,
    owners: Math.floor(Math.random() * 100000),
    totalAssets: Math.floor(Math.random() * 1000000),
  },
  {
    id: "6",
    collection: "PalioAI Aura",
    type: "ERC-721",
    volume: `${Math.random() * 100}`,
    change: `${Math.random() * 100}`,
    sales: Math.floor(Math.random() * 100),
    minPrice: `${Math.random() * 2}`,
    maxPrice: `${Math.random() * 10}`,
    transfer: `${Math.random() * 1000}`,
    owners: Math.floor(Math.random() * 100000),
    totalAssets: Math.floor(Math.random() * 1000000),
  },
  {
    id: "7",
    collection: "ParallelPlanetfall",
    type: "ERC-1155",
    volume: `${Math.random() * 100}`,
    change: `${Math.random() * 100}`,
    sales: Math.floor(Math.random() * 100),
    minPrice: `${Math.random() * 2}`,
    maxPrice: `${Math.random() * 10}`,
    transfer: `${Math.random() * 1000}`,
    owners: Math.floor(Math.random() * 100000),
    totalAssets: Math.floor(Math.random() * 1000000),
  },
  {
    id: "8",
    collection: "MutantApeYachtClub",
    type: "ERC-721",
    volume: `${Math.random() * 100}`,
    change: `${Math.random() * 100}`,
    sales: Math.floor(Math.random() * 100),
    minPrice: `${Math.random() * 2}`,
    maxPrice: `${Math.random() * 10}`,
    transfer: `${Math.random() * 1000}`,
    owners: Math.floor(Math.random() * 100000),
    totalAssets: Math.floor(Math.random() * 1000000),
  },
  {
    id: "9",
    collection: "Art Blocks",
    type: "ERC-721",
    volume: `${Math.random() * 100}`,
    change: `${Math.random() * 100}`,
    sales: Math.floor(Math.random() * 100),
    minPrice: `${Math.random() * 2}`,
    maxPrice: `${Math.random() * 10}`,
    transfer: `${Math.random() * 1000}`,
    owners: Math.floor(Math.random() * 100000),
    totalAssets: Math.floor(Math.random() * 1000000),
  },
  {
    id: "10",
    collection: "Art Blocks",
    type: "ERC-721",
    volume: `${Math.random() * 100}`,
    change: `${Math.random() * 100}`,
    sales: Math.floor(Math.random() * 100),
    minPrice: `${Math.random() * 2}`,
    maxPrice: `${Math.random() * 10}`,
    transfer: `${Math.random() * 1000}`,
    owners: Math.floor(Math.random() * 100000),
    totalAssets: Math.floor(Math.random() * 1000000),
  },
  {
    id: "11",
    collection: "OVERWORLD INCARNA",
    type: "ERC-721",
    volume: `${Math.random() * 100}`,
    change: `${Math.random() * 100}`,
    sales: Math.floor(Math.random() * 100),
    minPrice: `${Math.random() * 2}`,
    maxPrice: `${Math.random() * 10}`,
    transfer: `${Math.random() * 1000}`,
    owners: Math.floor(Math.random() * 100000),
    totalAssets: Math.floor(Math.random() * 1000000),
  },
];
const dataFor7D = [
  {
    id: "1",
    collection: "BoredApeYachtClub",
    type: "ERC-721",
    volume: `${Math.random() * 100}`,
    change: `${Math.random() * 100}`,
    sales: Math.floor(Math.random() * 100),
    minPrice: `${Math.random() * 2}`,
    maxPrice: `${Math.random() * 10}`,
    transfer: `${Math.random() * 1000}`,
    owners: Math.floor(Math.random() * 100000),
    totalAssets: Math.floor(Math.random() * 1000000),
  },
  {
    id: "2",
    collection: "MutantApeYachtClub",
    type: "ERC-721",
    volume: `${Math.random() * 100}`,
    change: `${Math.random() * 100}`,
    sales: Math.floor(Math.random() * 100),
    minPrice: `${Math.random() * 2}`,
    maxPrice: `${Math.random() * 10}`,
    transfer: `${Math.random() * 1000}`,
    owners: Math.floor(Math.random() * 100000),
    totalAssets: Math.floor(Math.random() * 1000000),
  },
  {
    id: "3",
    collection: "Azuki",
    type: "ERC-721",
    volume: `${Math.random() * 100}`,
    change: `${Math.random() * 100}`,
    sales: Math.floor(Math.random() * 100),
    minPrice: `${Math.random() * 2}`,
    maxPrice: `${Math.random() * 10}`,
    transfer: `${Math.random() * 1000}`,
    owners: Math.floor(Math.random() * 100000),
    totalAssets: Math.floor(Math.random() * 1000000),
  },
  {
    id: "4",
    collection: "PalioAI Aura",
    type: "ERC-721",
    volume: `${Math.random() * 100}`,
    change: `${Math.random() * 100}`,
    sales: Math.floor(Math.random() * 100),
    minPrice: `${Math.random() * 2}`,
    maxPrice: `${Math.random() * 10}`,
    transfer: `${Math.random() * 1000}`,
    owners: Math.floor(Math.random() * 100000),
    totalAssets: Math.floor(Math.random() * 1000000),
  },
  {
    id: "5",
    collection: "ProphetBots",
    type: "ERC-1155",
    volume: `${Math.random() * 100}`,
    change: `${Math.random() * 100}`,
    sales: Math.floor(Math.random() * 100),
    minPrice: `${Math.random() * 2}`,
    maxPrice: `${Math.random() * 10}`,
    transfer: `${Math.random() * 1000}`,
    owners: Math.floor(Math.random() * 100000),
    totalAssets: Math.floor(Math.random() * 1000000),
  },
  {
    id: "6",
    collection: "Art Blocks",
    type: "ERC-721",
    volume: `${Math.random() * 100}`,
    change: `${Math.random() * 100}`,
    sales: Math.floor(Math.random() * 100),
    minPrice: `${Math.random() * 2}`,
    maxPrice: `${Math.random() * 10}`,
    transfer: `${Math.random() * 1000}`,
    owners: Math.floor(Math.random() * 100000),
    totalAssets: Math.floor(Math.random() * 1000000),
  },
  {
    id: "7",
    collection: "PudgyPenguins",
    type: "ERC-721",
    volume: `${Math.random() * 100}`,
    change: `${Math.random() * 100}`,
    sales: Math.floor(Math.random() * 100),
    minPrice: `${Math.random() * 2}`,
    maxPrice: `${Math.random() * 10}`,
    transfer: `${Math.random() * 1000}`,
    owners: Math.floor(Math.random() * 100000),
    totalAssets: Math.floor(Math.random() * 1000000),
  },
  {
    id: "8",
    collection: "SOMO Monoliths",
    type: "ERC-721",
    volume: `${Math.random() * 100}`,
    change: `${Math.random() * 100}`,
    sales: Math.floor(Math.random() * 100),
    minPrice: `${Math.random() * 2}`,
    maxPrice: `${Math.random() * 10}`,
    transfer: `${Math.random() * 1000}`,
    owners: Math.floor(Math.random() * 100000),
    totalAssets: Math.floor(Math.random() * 1000000),
  },
  {
    id: "9",
    collection: "CHuBBiT Official Collection",
    type: "ERC-721",
    volume: `${Math.random() * 100}`,
    change: `${Math.random() * 100}`,
    sales: Math.floor(Math.random() * 100),
    minPrice: `${Math.random() * 2}`,
    maxPrice: `${Math.random() * 10}`,
    transfer: `${Math.random() * 1000}`,
    owners: Math.floor(Math.random() * 100000),
    totalAssets: Math.floor(Math.random() * 1000000),
  },
  {
    id: "10",
    collection: "TAROT",
    type: "ERC-721",
    volume: `${Math.random() * 100}`,
    change: `${Math.random() * 100}`,
    sales: Math.floor(Math.random() * 100),
    minPrice: `${Math.random() * 2}`,
    maxPrice: `${Math.random() * 10}`,
    transfer: `${Math.random() * 1000}`,
    owners: Math.floor(Math.random() * 100000),
    totalAssets: Math.floor(Math.random() * 1000000),
  },
  {
    id: "11",
    collection: "My Pet Hooligan",
    type: "ERC-721",
    volume: `${Math.random() * 100}`,
    change: `${Math.random() * 100}`,
    sales: Math.floor(Math.random() * 100),
    minPrice: `${Math.random() * 2}`,
    maxPrice: `${Math.random() * 10}`,
    transfer: `${Math.random() * 1000}`,
    owners: Math.floor(Math.random() * 100000),
    totalAssets: Math.floor(Math.random() * 1000000),
  },
];
const dataFor30D = [
  {
    id: "1",
    collection: "BoredApeYachtClub",
    type: "ERC-721",
    volume: `${Math.random() * 100}`,
    change: `${Math.random() * 100}`,
    sales: Math.floor(Math.random() * 100),
    minPrice: `${Math.random() * 2}`,
    maxPrice: `${Math.random() * 10}`,
    transfer: `${Math.random() * 1000}`,
    owners: Math.floor(Math.random() * 100000),
    totalAssets: Math.floor(Math.random() * 1000000),
  },
  {
    id: "2",
    collection: "MutantApeYachtClub",
    type: "ERC-721",
    volume: `${Math.random() * 100}`,
    change: `${Math.random() * 100}`,
    sales: Math.floor(Math.random() * 100),
    minPrice: `${Math.random() * 2}`,
    maxPrice: `${Math.random() * 10}`,
    transfer: `${Math.random() * 1000}`,
    owners: Math.floor(Math.random() * 100000),
    totalAssets: Math.floor(Math.random() * 1000000),
  },
  {
    id: "3",
    collection: "KnownOriginDigitalAsset",
    type: "ERC-721",
    volume: `${Math.random() * 100}`,
    change: `${Math.random() * 100}`,
    sales: Math.floor(Math.random() * 100),
    minPrice: `${Math.random() * 2}`,
    maxPrice: `${Math.random() * 10}`,
    transfer: `${Math.random() * 1000}`,
    owners: Math.floor(Math.random() * 100000),
    totalAssets: Math.floor(Math.random() * 1000000),
  },
  {
    id: "4",
    collection: "Art Blocks",
    type: "ERC-1155",
    volume: `${Math.random() * 100}`,
    change: `${Math.random() * 100}`,
    sales: Math.floor(Math.random() * 100),
    minPrice: `${Math.random() * 2}`,
    maxPrice: `${Math.random() * 10}`,
    transfer: `${Math.random() * 1000}`,
    owners: Math.floor(Math.random() * 100000),
    totalAssets: Math.floor(Math.random() * 1000000),
  },
  {
    id: "5",
    collection: "Azuki",
    type: "ERC-721",
    volume: `${Math.random() * 100}`,
    change: `${Math.random() * 100}`,
    sales: Math.floor(Math.random() * 100),
    minPrice: `${Math.random() * 2}`,
    maxPrice: `${Math.random() * 10}`,
    transfer: `${Math.random() * 1000}`,
    owners: Math.floor(Math.random() * 100000),
    totalAssets: Math.floor(Math.random() * 1000000),
  },
  {
    id: "6",
    collection: "PudgyPenguins",
    type: "ERC-721",
    volume: `${Math.random() * 100}`,
    change: `${Math.random() * 100}`,
    sales: Math.floor(Math.random() * 100),
    minPrice: `${Math.random() * 2}`,
    maxPrice: `${Math.random() * 10}`,
    transfer: `${Math.random() * 1000}`,
    owners: Math.floor(Math.random() * 100000),
    totalAssets: Math.floor(Math.random() * 1000000),
  },
  {
    id: "7",
    collection: "My Pet Hooligan",
    type: "ERC-721",
    volume: `${Math.random() * 100}`,
    change: `${Math.random() * 100}`,
    sales: Math.floor(Math.random() * 100),
    minPrice: `${Math.random() * 2}`,
    maxPrice: `${Math.random() * 10}`,
    transfer: `${Math.random() * 1000}`,
    owners: Math.floor(Math.random() * 100000),
    totalAssets: Math.floor(Math.random() * 1000000),
  },
  {
    id: "8",
    collection: "OVERWORLD INCARNA",
    type: "ERC-721",
    volume: `${Math.random() * 100}`,
    change: `${Math.random() * 100}`,
    sales: Math.floor(Math.random() * 100),
    minPrice: `${Math.random() * 2}`,
    maxPrice: `${Math.random() * 10}`,
    transfer: `${Math.random() * 1000}`,
    owners: Math.floor(Math.random() * 100000),
    totalAssets: Math.floor(Math.random() * 1000000),
  },
  {
    id: "9",
    collection: "Art Blocks",
    type: "ERC-721",
    volume: `${Math.random() * 100}`,
    change: `${Math.random() * 100}`,
    sales: Math.floor(Math.random() * 100),
    minPrice: `${Math.random() * 2}`,
    maxPrice: `${Math.random() * 10}`,
    transfer: `${Math.random() * 1000}`,
    owners: Math.floor(Math.random() * 100000),
    totalAssets: Math.floor(Math.random() * 1000000),
  },
  {
    id: "10",
    collection: "CHuBBiT Official Collection",
    type: "ERC-721",
    volume: `${Math.random() * 100}`,
    change: `${Math.random() * 100}`,
    sales: Math.floor(Math.random() * 100),
    minPrice: `${Math.random() * 2}`,
    maxPrice: `${Math.random() * 10}`,
    transfer: `${Math.random() * 1000}`,
    owners: Math.floor(Math.random() * 100000),
    totalAssets: Math.floor(Math.random() * 1000000),
  },
  {
    id: "11",
    collection: "Lasogette NFT",
    type: "ERC-721",
    volume: `${Math.random() * 100}`,
    change: `${Math.random() * 100}`,
    sales: Math.floor(Math.random() * 100),
    minPrice: `${Math.random() * 2}`,
    maxPrice: `${Math.random() * 10}`,
    transfer: `${Math.random() * 1000}`,
    owners: Math.floor(Math.random() * 100000),
    totalAssets: Math.floor(Math.random() * 1000000),
  },
];

const TopNFTsPage = () => {
  const { theme } = useTheme();
  const { t } = useTranslation();
  const [isSelectedTime, setIsSelectedTime] = useState(0);
  const [dataTable, setDataTable] = useState(dataFor1H);

  const handleSelectTime = (index: number) => {
    setIsSelectedTime(index);
    switch (FILTER_TIME_DATA[index]) {
      case FILTER_TIME_DATA[1]:
        setDataTable(dataFor6H);
        break;
      case FILTER_TIME_DATA[2]:
        setDataTable(dataFor12H);
        break;
      case FILTER_TIME_DATA[3]:
        setDataTable(dataFor1D);
        break;
      case FILTER_TIME_DATA[4]:
        setDataTable(dataFor7D);
        break;
      case FILTER_TIME_DATA[5]:
        setDataTable(dataFor30D);
        break;
      default:
        setDataTable(dataFor1H);
        break;
    }
  };

  return (
    <ScanLayout containerStyle="bg-[#FAFAFA] dark:bg-[#181818] dark:bg-primaryDark font-sans-serif relative">
      <div className="container-xxl">
        <div className="flex flex-col gap-4 md:gap-6 px-3  md:px-0 lg:px-0">
          <div>
            <div className="py-5 flex flex-col  gap-2 border-b border-b-[#e9ecef] dark:border-b-[#222]">
              <div className="flex ">
                <h1 className="text-[18.75px] font-bold mr-1 text-[#212529] dark:text-[#FAFAFA]">
                  {t("topNFTs.title")}
                </h1>
              </div>
            </div>
          </div>
          <div className="flex items-center justify-end">
            <FilterTime
                onClickTime={handleSelectTime}
                isSelect={isSelectedTime}
                filterTimeData={FILTER_TIME_DATA}
            />
          </div>
          <TopNFTsTable defaultData={dataTable} />
        </div>
      </div>
    </ScanLayout>
  );
};

export default TopNFTsPage;
